name: Alpine Interchange
favicon: null
layout_spectrum: 0.885428145993501
typography_spectrum: 0.36629462195560336
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.40238903067074716
  lightness: 0.9088180493563414
  saturation: 0.01767749711871147
  rhythmicContrast: 0.834334967425093
purpose: []
